Modify CI.yml

diff --git a/crates/pyburn-vision/.github/workflows/CI.yml b/crates/pyburn-vision/.github/workflows/CI.yml
--- a/crates/pyburn-vision/.github/workflows/CI.yml
+++ b/crates/pyburn-vision/.github/workflows/CI.yml
@@ -41,6 +41,31 @@ jobs:
       - uses: actions/setup-python@v5
         with:
           python-version: 3.x
+
+      - name: Install dependencies linux
+        run: |
+          max_retries=5
+          retry_delay=10
+          for i in $(seq 1 $max_retries); do
+              echo "Attempt $i: Updating package lists..."
+              if sudo apt-get update -y; then
+                  echo "Package lists updated successfully."
+                  break
+              fi
+              echo "apt-get update failed. Retrying in $retry_delay seconds..."
+              sleep $retry_delay
+          done
+          if [ $i -eq $max_retries ]; then
+              echo "ERROR: Failed to update package lists after $max_retries attempts."
+              exit 1
+          fi
+          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+              pkg-config \
+              libssl-dev \
+              build-essential \
+              libffi-dev \
+              python3-dev 
+          sudo rm -rf /var/lib/apt/lists/*
       - name: Build wheels
         uses: PyO3/maturin-action@v1
         with:
@@ -48,6 +73,8 @@ jobs:
           args: --release --out dist --find-interpreter
           sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
           manylinux: auto
+        
+        
       - name: Upload wheels
         uses: actions/upload-artifact@v4
         with:
@@ -72,6 +99,32 @@ jobs:
       - uses: actions/setup-python@v5
         with:
           python-version: 3.x
+
+      - name: Install deps muslinux
+        run: |
+          max_retries=5
+          retry_delay=10
+          for i in $(seq 1 $max_retries); do
+              echo "Attempt $i: Updating package lists..."
+              if sudo apt-get update -y; then
+                  echo "Package lists updated successfully."
+                  break
+              fi
+              echo "apt-get update failed. Retrying in $retry_delay seconds..."
+              sleep $retry_delay
+          done
+          if [ $i -eq $max_retries ]; then
+              echo "ERROR: Failed to update package lists after $max_retries attempts."
+              exit 1
+          fi
+          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+              pkg-config \
+              libssl-dev \
+              build-essential \
+              libffi-dev \
+              python3-dev 
+          cargo b --verbose
+          sudo rm -rf /var/lib/apt/lists/*
       - name: Build wheels
         uses: PyO3/maturin-action@v1
         with:
@@ -142,6 +195,30 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      - name: Install deps
+        run: |
+          max_retries=5
+          retry_delay=10
+          for i in $(seq 1 $max_retries); do
+              echo "Attempt $i: Updating package lists..."
+              if sudo apt-get update -y; then
+                  echo "Package lists updated successfully."
+                  break
+              fi
+              echo "apt-get update failed. Retrying in $retry_delay seconds..."
+              sleep $retry_delay
+          done
+          if [ $i -eq $max_retries ]; then
+              echo "ERROR: Failed to update package lists after $max_retries attempts."
+              exit 1
+          fi
+          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+              pkg-config \
+              libssl-dev \
+              build-essential \
+              libffi-dev \
+              python3-dev 
+          sudo rm -rf /var/lib/apt/lists/*
       - name: Build sdist
         uses: PyO3/maturin-action@v1
         with:
